config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :dropbox, only: [:index]

  controller 'dropbox' do
    get 'dropbox/file_download/*path' => 'dropbox#file_download', as: 'file_download', constraints: { path: /.*/ }
    get 'dropbox/auth' => 'dropbox#auth'
    get 'dropbox/auth_callback' => 'dropbox#auth_callback'
    get 'dropbox/disconnect' => 'dropbox#disconnect'
  end

  resources :wunderlist, only: [:index]

  get 'wunderlist/auth' => 'wunderlist#auth'
  get 'wunderlist/auth_callback' => 'wunderlist#auth_callback'
  get 'wunderlist/disconnect' => 'wunderlist#disconnect'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token_user.rb
class TokenUser < ApplicationRecord
  belongs_to :user

  # This enum should add a new token type when we add a new service support
  enum token_type: [ :dropbox, :wunderlist ]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :token_users

  def authenticated_with? service_name
    TokenUser.find_by(user: self, token_type: TokenUser.token_types[service_name]).try(:token).present?
  end
end

app/models/wrappers/dropbox_wrapper.rb
class DropboxWrapper < ServiceWrapper

  NAME = :dropbox

  def initialize(token: token)
    @client = DropboxApi::Client.new(token)
  end

  def entries(route: "")
    @result = @client.list_folder route

    @result.entries
  end

  def item_type entry
    entry.is_a?(DropboxApi::Metadata::Folder) ? 'folder' : 'file'
  end

  def name
    @client.get_current_account.name.display_name
  end

  def render_file(path: path)
    file_contents = ""
    @client.download("/#{path}") do |chunk|
      file_contents << chunk
    end

    file_contents
  end
end

app/models/wrappers/service_wrapper.rb
class ServiceWrapper

  def object
    @client
  end

  def self.persist_token!(user: user, token: token, token_type: token_type)
    # Persist token for user
    TokenUser.create!(user: user, token: token, token_type: TokenUser.token_types[self::NAME])
  end
end

app/models/wrappers/wunderlist_wrapper.rb
class WunderlistWrapper < ServiceWrapper

  NAME = :wunderlist

  def initialize(token: token)
    @client = Wunderlist::API.new({client_id: Settings.wunderlist.app_id, access_token: token})
  end

  def self.generate_random
    (0...50).map { ('a'..'z').to_a[rand(26)] }.join
  end

  def name
    @client.user.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /<service>/auth
  def auth
    if current_user.authenticated_with? (controller_name.to_sym)
      render :index
    else
      redirect_to auth_url
    end
  end

  def index
    @client = "#{controller_name}Wrapper".classify.constantize.new(token: token) if current_user.authenticated_with? (controller_name.to_sym)
  end

  def disconnect
    TokenUser.destroy_all(user: current_user, token_type: TokenUser.token_types[controller_name.to_sym])

    redirect_to send("#{controller_name}_index_path"), alert: "Your #{controller_name} account has been disconnected"
  end

  protected

  def token
    TokenUser.find_by(user: current_user, token_type: TokenUser.token_types[controller_name.to_sym]).try(:token)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/dropbox_controller.rb
class DropboxController < ApplicationController
  before_action :authenticate_user!

  # GET /dropbox/auth_callback?code=SoMeToKeN
  def auth_callback
    begin
      auth_bearer = authenticator.get_token(params[:code], redirect_uri: redirect_uri)
      token = auth_bearer.token

      DropboxWrapper.persist_token!(user: current_user, token: token)

      flash[:notice] = "Your dropbox account has been connected successfully"
    rescue => err
      logger.error err.message
      flash[:error] = "Your dropbox account could not be connected"
    end

    redirect_to dropbox_index_path
  end

  def file_download
    # TODO Create a singleton of client so I don't have to instanciate it every time
    client = DropboxWrapper.new(token: token)
    file_contents = client.render_file path: params[:path]

    send_data file_contents, filename: params[:path], disposition: 'attachment'
  end

  private

  def auth_url
    authenticator.authorize_url(redirect_uri: redirect_uri)
  end

  def authenticator
    DropboxApi::Authenticator.new(Settings.dropbox.app_id, Settings.dropbox.app_secret)
  end

  def redirect_uri
    Settings.dropbox.app_auth_callback_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, alert: "Access denied"
    end
  end

end

app/controllers/wunderlist_controller.rb
class WunderlistController < ApplicationController
  before_action :authenticate_user!

  # GET /wunderlist/auth_callback?state=SoMeRanDomStriNg&code=SoMeCoDe
  def auth_callback
  # TODO consider params[:state]; if it don't match request was created by a third party and the process should abort.
    conn = Faraday.new(url: authenticator.site) do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
    end

    response = conn.post authenticator.token_url, { code: params[:code],
                                                    client_secret: Settings.wunderlist.app_secret,
                                                    client_id: Settings.wunderlist.app_id }
    parsed_response = JSON::parse response.body
    WunderlistWrapper.persist_token!(user: current_user, token: parsed_response["access_token"])

    redirect_to wunderlist_index_path, notice: "Your wunderlist account has been connected successfully"
  end


  private

  def auth_url
    # Wunderlist auth expects a random string
    random = WunderlistWrapper.generate_random

    "#{authenticator.authorize_url}?client_id=#{Settings.wunderlist.app_id}&redirect_uri=#{redirect_uri}&state=#{random}"
  end

  def authenticator
    OmniAuth::Strategies::Wunderlist.new({}).options.client_options
  end

  def redirect_uri
    Settings.wunderlist.app_auth_callback_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_back.html.erb
<p><%= link_to "< Go back", root_path %> </p>

app/views/application/_title.html.erb
<h3><%= "Hey there, #{@client.name}!" %></h3>

app/views/application/index.html.erb
<div class="col-sm-12">
  <% if current_user.authenticated_with? controller_name.to_sym %>
      <div><%= link_to "#{controller_name.capitalize} << Logout", send("#{controller_name}_disconnect_path"), class: "btn-sm btn-danger" %></div>
      <%= render 'title' %>
      <%= render partial: "#{controller_name}/list" %>
  <% else %>
      <p><%= link_to "#{controller_name.capitalize} >> Login", send("#{controller_name}_auth_path"), class: "btn-sm btn-success" %></p>
  <% end %>

  <%= render 'back' %>
</div>

app/views/dropbox/_file.html.erb
<li><%= f.name %> [ <%= link_to 'download', file_download_path(path: f.path_lower), class: "btn-xs btn-info" %> ]</li>

app/views/dropbox/_folder.html.erb
<li><strong>Folder: </strong><%= f.name %></li>
<ul>
  <%= render partial: 'items', locals: { items: @client.entries(route: f.path_lower) } %>
</ul>

app/views/dropbox/_items.html.erb
<%- items.entries.each do |item| %>
  <%= render partial: @client.item_type(item), locals:{ f: item } %>
<% end %>

app/views/dropbox/_list.html.erb
<div>
  <p class="well">You have uploaded the following content to your Dropbox account:</p>
  <ul>
    <%= render partial: 'items', locals: {items: @client.entries } %>
  </ul>
</div>

app/views/home/index.html.erb
<div class="row">
  <h1><%= image_tag('mailbutler.png', width:"100", height:"100") %></h1>
  <div class="col-sm-12 text-xs-center col-sm-offset-3">
    <h1>Welcome to MailButler!</h1>
    <p class="lead">Your personal assistant for efficient and productive work.</p>
  </div>
</div>

<div class="jumbotron">
  <div class="col-sm-12 well">
    <div class="text-center">
      <%= link_to "Dropbox!", dropbox_index_path, class: "btn-lg btn-warning"  %>
      <%= link_to "Wunderlist!", wunderlist_index_path, class: "btn-lg btn-info" %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MailButler | Feingeist Project" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/wunderlist/_list.html.erb
<div>
  <p class="well">You have all this lists waiting for you:</p>
  <% @client.object.lists.each do |list| %>
    <ul>
      <li>
        <%- if list.tasks.empty? %>
          <%= list.title %> - [Empty list]
        <% else %>
          <%= render partial: 'tasks', locals: { list: list } %>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

app/views/wunderlist/_task.html.erb
<ul class="list-group">
  <li class="list-group-item">Title: <%= task.title %></li>
  <li class="list-group-item">Due date: <%= task.due_date %></li>
  <li class="list-group-item">Status:
    <% if task.completed %>
      Completed! (<%= task.completed_at %>)
    <% else %>
      Pending...
  </li>
    <% end %>
  <li class="list-group-item">Comments: <%= task.task_comments %></li>
</ul>

app/views/wunderlist/_tasks.html.erb
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="<%="heading#{list.id}"%>">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse#{list.id}" %>" aria-expanded="false" aria-controls="<%= "collapse#{list.id}"%>">
          <%= list.title %>
        </a>
      </h5>
    </div>
    <div id="<%= "collapse#{list.id}" %>" class="collapse" role="tabpanel" aria-labelledby="<%="heading#{list.id}"%>">
      <div class="card-block">
        <% list.tasks.each do |task| %>
          <%= render partial: 'task', locals: { task: task } %>
        <% end %>
      </div>
    </div>
  </div>
</div>